// constants/permissions.js
import { ROLES } from "./Role";

export const PERMISSIONS = {
  [ROLES.ADMIN]: [
    "/insurance",
    "/mobile-missing-report",
    "/dead-body-reports",
    "/missing-person",
    "/missing-vehicle",
    "/unclaimed-vehicle",
    "/accident-vehicle",
    "/bulkcheck-logs",
    "/blackmail",
    "/accountfreeze",
    "/cyberfraud",
    "/content-takedown",
    // "/face-matching",
    "/volunteer",
    "/bulkcheck",
    "/complain",
    "/course",
    "/app-version",
    "/send-notification",
    "/ground-verification",
    "/gallery",
    "/dashboard",
    "/client-payment",
    "/client-wallet",
    "/get-all-clients",
    "/client-api-hit",
    "/api-keys",
    "/api-hit-logs",
    "/override-price",
    "/banners",
    "/announcement",
    "/payments",
    "/vandor-out-standing",
    "/vandor-payment",
    "/aadhar",
    "/pan",
    "/ration",
    "/other-vehicle",
    "/other",
    "/tracking",
    "/api-key-access",
    "/get-client-wallet",
    "/get-api-hit",
    "/mobile",
    "/api-hit-logs",
    "/api-keys",
    "/search-by-aadhar",
    "/search-by-pan",
    "/search-by-mobile",
    "/search-by-vehicle",
    "/company-background-check",
    // "/api-uses-log",

    // "/customer-verification",
    "/digital-footprint",
    // "/mobile-lookup",
    // "/business-verification",
    // "/vehicle-lookup",
    // "/financial-check",
    "/background-check",
    "/digox-check",
    "/mobile-superior",
    "/bankVpa-credit",
    "/whatsapp-gmail-check",
    "/multiple-vehicle",
    "/uan",
    // "/utility-check",
    "/settings",
    "/logout",
  ],

  [ROLES.POLICE]: [
    "/dashboard",
    "/mobile-superior",
    "/background-check",
    "/whatsapp-gmail-check",
    "/face-matching",
    "/logout",
  ],

  [ROLES.USER]: [
    // "/dashboard",
    "/api-logs",
    "/client-api-key-access",
    "/profile",
    "/wallet-balance",
    "/api-keys-access",
    "/aadhar",
    "/pan",
    "/ration",
    "/other",
    "/tracking",
    "/mobile-lookup",
    "/digital-footprint",
    "/background-check",
    "/mobile-superior",
    "/mobile",
    "/bankVpa-credit",
    "/uan",
    "/whatsapp-gmail-check",
    "/multiple-vehicle",
    "/company-background-check",
    "/search-by-aadhar",
    "/search-by-pan",
    "/search-by-mobile",
    "/search-by-vehicle",
    // "/customer-verification",
    "/mobile-lookup",
    "/logout",
  ],
};
